import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

// throw new Error("failed pana")

const About = () => {
  return <div>About</div>;
};

export default About;
